# Generated by Django 5.2.10 on 2026-03-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="text",
            field=models.TextField(
                help_text="Message content, max 50k chars", max_length=50000
            ),
        ),
        migrations.AlterField(
            model_name="chatsession",
            name="session_id",
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session", "-timestamp"], name="chat_chatme_session_6c4acb_idx"
            ),
        ),
    ]
