# Generated by Django 5.1.7 on 2026-03-22 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_alter_chatmessage_text_alter_chatsession_session_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="text",
            field=models.TextField(
                help_text="Message content, max 10k chars", max_length=10000
            ),
        ),
    ]
