# Generated by Django 5.2.10 on 2026-03-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventorytransaction",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="laborentry",
            name="date",
            field=models.DateField(db_index=True),
        ),
    ]
