# Generated by Django 5.2.10 on 2026-03-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field", "0004_fielddata_updated_at_pest_field_and_more"),
        ("planning", "0002_alter_inventorytransaction_date_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="equipmentbooking",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_datetime__gt", models.F("start_datetime"))),
                name="booking_end_after_start",
            ),
        ),
    ]
