# Generated by Django 5.2.10 on 2026-03-01 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field", "0002_irrigationlog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldalert",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="fieldlog",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="irrigationlog",
            name="date",
            field=models.DateField(db_index=True),
        ),
    ]
