# Generated by Django 5.2.10 on 2026-03-08 13:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field", "0003_alter_fieldalert_date_alter_fieldlog_date_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fielddata",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="pest",
            name="field",
            field=models.ForeignKey(
                blank=True,
                help_text="The field this pest report is associated with",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="pest_reports",
                to="field.fielddata",
            ),
        ),
        migrations.AlterField(
            model_name="fielddata",
            name="cropType",
            field=models.CharField(db_column="cropType", max_length=32),
        ),
        migrations.AlterField(
            model_name="fieldlog",
            name="activity",
            field=models.CharField(
                choices=[
                    ("watering", "Watering"),
                    ("fertilizer", "Fertilizer"),
                    ("sowing", "Sowing"),
                    ("pesticide", "Pesticide"),
                    ("harvest", "Harvest"),
                    ("other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="fielddata",
            index=models.Index(
                fields=["user", "created_at"], name="field_field_user_id_2176a1_idx"
            ),
        ),
    ]
