# Generated by Django 5.2.10 on 2026-03-09 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field", "0004_fielddata_updated_at_pest_field_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="fieldalert",
            index=models.Index(
                fields=["user", "is_read", "-date"],
                name="field_field_user_id_7ad45b_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="fieldlog",
            index=models.Index(
                fields=["user", "field", "-date"], name="field_field_user_id_03698b_idx"
            ),
        ),
    ]
