# Generated by Django 5.1.7 on 2026-03-22 12:19

import field.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field", "0005_fieldalert_field_field_user_id_7ad45b_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fielddata",
            name="polygon",
            field=models.JSONField(validators=[field.validators.validate_polygon]),
        ),
    ]
