# Generated by Django 5.1.7 on 2026-03-26 08:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field", "0006_alter_fielddata_polygon"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CropHealthScan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image_path", models.ImageField(upload_to="ml_scans/")),
                (
                    "detected_disease",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("confidence_score", models.FloatField(blank=True, null=True)),
                ("recommendation", models.TextField(blank=True, null=True)),
                ("severity", models.CharField(default="LOW", max_length=20)),
                ("scanned_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "field",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_scans",
                        to="field.fielddata",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="health_scans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-scanned_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "field", "-scanned_at"],
                        name="field_croph_user_id_77e013_idx",
                    )
                ],
            },
        ),
    ]
