# Generated by Django 5.2.10 on 2026-03-09 06:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("field", "0005_fieldalert_field_field_user_id_7ad45b_idx_and_more"),
        ("finance", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="costentry",
            index=models.Index(
                fields=["user", "field", "-date"], name="finance_cos_user_id_9f4912_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="costentry",
            index=models.Index(
                fields=["user", "season", "category"],
                name="finance_cos_user_id_24d3e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="revenue",
            index=models.Index(
                fields=["user", "field", "-date"], name="finance_rev_user_id_b1b14b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="revenue",
            index=models.Index(
                fields=["user", "crop"], name="finance_rev_user_id_a2f00e_idx"
            ),
        ),
    ]
